version: '3'


services:
  redis:
    restart: always
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  web:
    restart: always
    container_name: 'web_library'
    build:
      context: .
      args:
        requirements: requirements/development.txt
    command: >
      bash -c "python3 manage.py makemigrations books && python3 manage.py migrate
      && python3 manage.py runserver 0.0.0.0:8001"
    ports:
     - '8001:8001'
    depends_on:
     - db_library
     - redis
    environment:
     - DJANGO_SETTINGS_MODULE=library.settings.dev

  db_library:
    restart: always
    container_name: 'db_library'
    image: 'postgres:latest'
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
     - ./.postgres-data:/var/lib/postgresql/data

  celery:
    restart: always
    build:
      context: .
    container_name: 'celery'
    command: celery -A library worker -l info
    depends_on:
      - db_library
      - redis
      - web
    environment:
      - DJANGO_SETTINGS_MODULE=library.settings.dev
  celery-beat:
    restart: always
    build:
      context: .
    container_name: 'celery-beat'
    command: celery -A library beat -l info
    depends_on:
      - db_library
      - redis
      - web
    environment:
      - DJANGO_SETTINGS_MODULE=library.settings.dev

  dashboard:
    restart: always
    build: .
    container_name: 'celery-dashboard'
    command: flower -A library --port=5554 --broker=redis://redis:6379/0
    ports:
      - 5554:5554
    environment:
      - DJANGO_SETTINGS_MODULE=library.settings.dev
    depends_on:
      - web
      - redis
      - celery
