version: '2'


services:
    web_library:
      restart: always
      build:
        context: .
        args:
          requirements: requirements/development.txt
      command: >
        bash -c "python3 manage.py migrate
        && python3 manage.py runserver 0.0.0.0:8001"
      ports:
       - '8001:8001'
      depends_on:
       - db_library
      volumes:
       - .:/code
      environment:
       - DJANGO_SETTINGS_MODULE=library.settings.dev

    db_library:
      restart: always
      image: 'postgres:latest'
      expose:
        - "5433"
      ports:
        - "5433:5433"
      command: -p 5433
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: postgres
      volumes:
       - ./.postgres-data:/var/lib/postgresql/data